name: 'Yamllint'
on:
  - pull_request
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Run lint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: './terms'
          yamllint_strict: false
          yamllint_comment: true
          yamllint_config_filepath: '.yamllint'
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
